# Pandas Series

In [1]:
# pandas series
# must need to import pandas
import pandas as pd
obj=pd.Series([4,6,7,6])
print (obj)

0    4
1    6
2    7
3    6
dtype: int64


# pandas Series has two things in one object¶


# 1 values

# 2 index

In [2]:
sales=pd.Series([100,200,300,400])
print(sales.values)
print(sales.index)

[100 200 300 400]
RangeIndex(start=0, stop=4, step=1)


In [3]:
sales=pd.Series([100,200,300,400] ,index=["jan","feb","march","april"])
print(sales)
print(sales.values)
print(sales.index)

jan      100
feb      200
march    300
april    400
dtype: int64
[100 200 300 400]
Index(['jan', 'feb', 'march', 'april'], dtype='object')


In [4]:
sales=pd.Series([100,200,300,400],index=["Jan","Feb","Mar","Apr"],name="4 month sales")
sales

Jan    100
Feb    200
Mar    300
Apr    400
Name: 4 month sales, dtype: int64

# create a pandas series to store a canteen data to hold values of how many sandwithes are sold each days (one week)

In [5]:
Sw=pd.Series([20, 30, 20, 25, 30, 40, 0],index = ['mon', 'tue', 'wed', 'thr','fri', 'sat', 'sun'])
Sw


mon    20
tue    30
wed    20
thr    25
fri    30
sat    40
sun     0
dtype: int64

In [6]:
print(Sw[1])
print(Sw["mon"])
print(Sw["tue"])


30
20
30


In [7]:
print(Sw[[3,5]])
print(Sw[["mon","sun"]])

thr    25
sat    40
dtype: int64
mon    20
sun     0
dtype: int64


# for providing multipe index for selecting element in an pd series, use array notation¶# 

In [8]:
print(Sw>20)
print(Sw[Sw>20])
print(Sw[Sw<10])
print()

mon    False
tue     True
wed    False
thr     True
fri     True
sat     True
sun    False
dtype: bool
tue    30
thr    25
fri    30
sat    40
dtype: int64
sun    0
dtype: int64



In [9]:
Sw*2
Sw=Sw*2
print(Sw)

mon    40
tue    60
wed    40
thr    50
fri    60
sat    80
sun     0
dtype: int64


In [10]:
print(Sw)

mon    40
tue    60
wed    40
thr    50
fri    60
sat    80
sun     0
dtype: int64


In [11]:
Sw=Sw/2
print(Sw)

mon    20.0
tue    30.0
wed    20.0
thr    25.0
fri    30.0
sat    40.0
sun     0.0
dtype: float64


In [12]:
print("mon" in Sw)
print("monday" in Sw)

True
False


In [13]:
#taking input from numpy arrays
import numpy as np

arr=np.array([4,5,6,7,8])
ind=np.array(["a","b","c","d","e"])
obj=pd.Series(arr,index=ind,name="data from numpy array")
print(obj)

a    4
b    5
c    6
d    7
e    8
Name: data from numpy array, dtype: int32


In [14]:
"b" in obj

True

In [15]:

sdata={"sindh":35000,"kpk":3000,"punjab":4500,"Balochistan":2000} #dic
tax=pd.Series(sdata) #data from numpy dic
print(tax)
print(tax.index)
print(tax.values)

sindh          35000
kpk             3000
punjab          4500
Balochistan     2000
dtype: int64
Index(['sindh', 'kpk', 'punjab', 'Balochistan'], dtype='object')
[35000  3000  4500  2000]


In [16]:
tax1=pd.Series(sdata,index=["punjab","sindh","kpk","Balochistan"])
print(tax1)

punjab          4500
sindh          35000
kpk             3000
Balochistan     2000
dtype: int64


In [17]:
tax1=pd.Series(sdata,index=["punjab","sindh","kpk","Balochistan","GB"])#NaN means values does not exist in pandas series.
print(tax1)
print(pd.isnull(tax1))
tax1.isnull()

punjab          4500.0
sindh          35000.0
kpk             3000.0
Balochistan     2000.0
GB                 NaN
dtype: float64
punjab         False
sindh          False
kpk            False
Balochistan    False
GB              True
dtype: bool


punjab         False
sindh          False
kpk            False
Balochistan    False
GB              True
dtype: bool

# Pandas Data frame

In [18]:
import pandas as pd 
apple=pd.Series([3,4,5,6])
orange=pd.Series([6,5,7,8])
data={"apple":apple,"orange":orange}
obj=pd.DataFrame(data)   #DataFrame is used for handle multi dimensional array
print (obj)

   apple  orange
0      3       6
1      4       5
2      5       7
3      6       8


In [19]:
data={"state":["ohio","ohio","ohio","nevada","nevada","nevada"],
     "year":[2000,2001,2003,2004,2005,2006],
     "pop":[1.3,1.4,1.5,3.2,6.1,4.2]}
frame=pd.DataFrame(data,index=["1st","2nd","3rd","4th","5th","6th"])
print(frame)

      state  year  pop
1st    ohio  2000  1.3
2nd    ohio  2001  1.4
3rd    ohio  2003  1.5
4th  nevada  2004  3.2
5th  nevada  2005  6.1
6th  nevada  2006  4.2


In [20]:
frame.head(6)

state  year  pop
1st    ohio  2000  1.3
2nd    ohio  2001  1.4
3rd    ohio  2003  1.5
4th  nevada  2004  3.2
5th  nevada  2005  6.1
6th  nevada  2006  4.2

In [21]:

frame1=pd.DataFrame(data,index=["1st","2nd","3rd","4th","5th","6th"],  columns=['year','state','pop'])
frame1.head()

year   state  pop
1st  2000    ohio  1.3
2nd  2001    ohio  1.4
3rd  2003    ohio  1.5
4th  2004  nevada  3.2
5th  2005  nevada  6.1

In [22]:
frame2=pd.DataFrame(data,index=["1st","2nd","3rd","4th","5th","6th"], columns=["year","state","pop","debt"])
frame2.head()

year   state  pop debt
1st  2000    ohio  1.3  NaN
2nd  2001    ohio  1.4  NaN
3rd  2003    ohio  1.5  NaN
4th  2004  nevada  3.2  NaN
5th  2005  nevada  6.1  NaN

In [23]:
frame2.columns

Index(['year', 'state', 'pop', 'debt'], dtype='object')

In [24]:
frame2.index

Index(['1st', '2nd', '3rd', '4th', '5th', '6th'], dtype='object')

In [25]:
frame2.debt


1st    NaN
2nd    NaN
3rd    NaN
4th    NaN
5th    NaN
6th    NaN
Name: debt, dtype: object

In [26]:
frame2["state"] # dictionary like notation to access or extract

1st      ohio
2nd      ohio
3rd      ohio
4th    nevada
5th    nevada
6th    nevada
Name: state, dtype: object

In [27]:
#there is another method ,attribute style of accessing 
frame2.state

1st      ohio
2nd      ohio
3rd      ohio
4th    nevada
5th    nevada
6th    nevada
Name: state, dtype: object

In [28]:
frame2.loc["1st"]#in pandas loc function is used for access all detail from any row and columns

year     2000
state    ohio
pop       1.3
debt      NaN
Name: 1st, dtype: object

In [29]:
frame2["debt"]=16.5 # column can be modified
frame2

year   state  pop  debt
1st  2000    ohio  1.3  16.5
2nd  2001    ohio  1.4  16.5
3rd  2003    ohio  1.5  16.5
4th  2004  nevada  3.2  16.5
5th  2005  nevada  6.1  16.5
6th  2006  nevada  4.2  16.5

In [39]:
import pandas as pd
import numpy as np
data={"state":["ohio","ohio","ohio","nevada","nevada","nevada"],
     "year":[2000,2001,2003,2004,2005,2006],
     "pop":[1.3,1.4,1.5,3.2,6.1,4.2]}
A=pd.DataFrame(data, columns=["state","year","pop","debt"],index=["one","two","three","four","five","six"])

B =(len(A))
rng=np.arange(B)
A["debt"]= rng
A

state  year  pop  debt
one      ohio  2000  1.3     0
two      ohio  2001  1.4     1
three    ohio  2003  1.5     2
four   nevada  2004  3.2     3
five   nevada  2005  6.1     4
six    nevada  2006  4.2     5

In [50]:
a=np.random.randn(4,4)

In [51]:
a

array([[-0.22017555, -0.33347375,  0.56450419, -0.03646985],
       [ 0.75339847,  0.88651763,  0.55469101,  0.85892093],
       [ 0.98626074,  1.18848381,  1.73949475,  0.86967368],
       [-0.23714346, -0.96009296,  0.17514776, -1.10197929]])

In [84]:
f=pd.DataFrame(np.random.randn(4,4), columns=list("abcd"),index=["otah","ohio","texas","origin"])
print (f)
#print(np.abs(f))
#print(f["d"].min())
#print(f["d"].max())
#print(f["d"].max()-f["d"].min())

d=lambda x: x.max() - x.min()
df=f.apply(d)
print(df,type(df))
#df=f.apply(d,axis=1)
#print(df)

#def min_max(x):
#    minimum=x.min()
 #   maximum=x.max()
 #   return pd.Series([x.min(),x.max()],index=["min","max"])
#df=f.apply(min_max)
#print (df,type(df))
    


               a         b         c         d
otah    1.250287 -0.871692  0.451599  0.532307
ohio   -0.733379  0.429053 -0.388501 -0.578974
texas   0.927478 -0.584543 -0.485704 -0.480972
origin  1.854952 -0.187395  0.266548 -0.088803
a    2.588331
b    1.300745
c    0.937303
d    1.111281
dtype: float64 <class 'pandas.core.series.Series'>


# Arithmetic & Data Alignment


In [10]:
import numpy as np
import pandas as pd

data_df = pd.DataFrame(np.arange(16).reshape((4, 4)), 
             index=['Ohio', 'Colorado', 'Utah', 'New York'],
             columns=['one', 'two', 'three', 'four'])

print(data_df, "\n")
# in the loc method specify row label first 
# then specify column names
# remember! mutiple column names require array notation
print( data_df.loc[['Colorado','Ohio'], ['two',  'three'] ] )
print("\n")
print( data_df.iloc[2:, [3, 0, 1] ] ) # using number instead of labels
print( data_df.iloc[:])
print ( data_df.iloc[ :3 , :3 ] )
print( data_df.iloc[:, :3])

          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15 

          two  three
Colorado    5      6
Ohio        1      2


          four  one  two
Utah        11    8    9
New York    15   12   13
          one  two  three  four
Ohio        0    1      2     3
Colorado    4    5      6     7
Utah        8    9     10    11
New York   12   13     14    15
          one  two  three
Ohio        0    1      2
Colorado    4    5      6
Utah        8    9     10
          one  two  three
Ohio        0    1      2
Colorado    4    5      6
Utah        8    9     10
New York   12   13     14
